// Generated by typings
// Source: https://raw.githubusercontent.com/dojo/typings/288d3a9868194f0e1ad6687371dffd1d96cb39a1/custom/dev/dev.d.ts
declare module 'intern/dojo/Promise' {
	import Promise = require('dojo/Promise');
	export = Promise;
}

declare module 'intern/lib/util' {
	export function getErrorMessage(error: any): string;
}

declare module 'intern/lib/reporters/Runner' {
	import charm = require('charm');
	class Runner {
		protected charm: charm.Charm;
		protected hasErrors: boolean;
		protected sessions: any;

		constructor(config?: any);
	}
	export = Runner;
}

declare module 'intern/lib/reporters/Combined' {
	class Combined {
		protected hasErrors: boolean;
		protected sessions: any;
		protected _writeLine(): void;
		protected output: { write(args: any[]): void; };

		constructor(config?: any);
	}
	export = Combined;
}

declare module 'intern/dojo/node!istanbul/lib/collector' {
	class Collector {
		add(coverage: any): void;
		files(): string[];
	}

	export = Collector;
}

declare module 'intern/dojo/node!istanbul/lib/report/json' {
	import Collector = require('intern/dojo/node!istanbul/lib/collector');
	class JsonReporter {
		constructor(options: any);

		writeReport(collector: Collector, sync: boolean): void;
	}
	export = JsonReporter;
}

declare module 'intern/dojo/node!istanbul/lib/instrumenter' {
	class Instrumenter {
		constructor(options?: any);

		instrumentSync(code: string, path: string): string;
		lastFileCoverage(): any;
	}
	export = Instrumenter;
}

declare module 'intern/dojo/node!istanbul/index' {
	let result: any;
	export = result;
}

declare module 'intern/dojo/node!glob' {
	const glob: {
		(pattern: string, callback: (err: Error, matches: string[]) => void): void;
		(pattern: string, options: any, callback: (err: Error, matches: string[]) => void): void;

		sync(pattern: string, options?: any): string[];
	};
	export = glob;
}

declare module 'charm' {
	import { Stream } from 'stream';

	const charm: {
		(): charm.Charm;
	};
	module charm {
		export interface Charm extends Stream {
			reset(): Charm;
			destroy(): void;
			end(): void;
			write(buf: string): Charm;
			display(attr: string): Charm;
			foreground(color: string|number): Charm;
			background(color: string|number): Charm;
		}
	}
	export = charm;
}

declare module 'intern/lib/util' {
	export function getErrorMessage(error: any): string;
}

declare module 'istanbul/lib/collector' {
	class Collector {
		add(coverage: any): void;
		files(): string[];
	}

	export = Collector;
}

declare module 'istanbul/lib/report/json' {
	import Collector = require('istanbul/lib/collector');
	class JsonReporter {
		constructor(options: any);

		writeReport(collector: Collector, sync: boolean): void;
	}
	export = JsonReporter;
}

declare module 'istanbul/lib/instrumenter' {
	class Instrumenter {
		constructor(options?: any);

		instrumentSync(code: string, path: string): string;
		lastFileCoverage(): any;
	}
	export = Instrumenter;
}

declare module 'istanbul/index' {
	let result: any;
	export = result;
}

declare module 'intern/dojo/node!fs' {
	import * as fs from 'fs';
	export = fs;
}

declare module 'intern/dojo/node!util' {
	import * as util from 'util';
	export = util;
}

declare module 'intern/dojo/node!path' {
	import * as path from 'path';
	export = path;
}